apiVersion: v1
kind: ConfigMap
metadata:
  name: ftrade-minibot-kucoin-xrpusdt-1m-env
  labels:
    app: ftrade-minibot
    exchange: "kucoin"
    pair: "XRPUSDT"
    timeframe: "1m"
data:
  EXCHANGE: "kucoin"
  SYMBOL: "XRPUSDT"
  INTERVAL: "1m"
  REMOTE_OPTIMIZER_PORT: "4500"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftrade-minibot-kucoin-xrpusdt-1m
  labels:
    app: ftrade-minibot
    exchange: "kucoin"
    pair: "XRPUSDT"
    timeframe: "1m"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftrade-minibot
      instance: "ftrade-minibot-kucoin-xrpusdt-1m"
  template:
    metadata:
      labels:
        app: ftrade-minibot
        instance: "ftrade-minibot-kucoin-xrpusdt-1m"
    spec:
      containers:
        - name: minibot
          image: "chaiya0899223232/ftrade-mini-bot:latest"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: ftrade-minibot-kucoin-xrpusdt-1m-env
            - secretRef:
                name: ftrade-minibot-kucoin-secret
