apiVersion: v1
kind: ConfigMap
metadata:
  name: ftrade-minibot-binance-ethusdt-5m-env
  labels:
    app: ftrade-minibot
    exchange: "binance"
    pair: "ETHUSDT"
    timeframe: "5m"
data:
  EXCHANGE: "binance"
  SYMBOL: "ETHUSDT"
  INTERVAL: "5m"
  REMOTE_OPTIMIZER_PORT: "4500"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftrade-minibot-binance-ethusdt-5m
  labels:
    app: ftrade-minibot
    exchange: "binance"
    pair: "ETHUSDT"
    timeframe: "5m"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftrade-minibot
      instance: "ftrade-minibot-binance-ethusdt-5m"
  template:
    metadata:
      labels:
        app: ftrade-minibot
        instance: "ftrade-minibot-binance-ethusdt-5m"
    spec:
      containers:
        - name: minibot
          image: "chaiya0899223232/ftrade-mini-bot:latest"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: ftrade-minibot-binance-ethusdt-5m-env
            - secretRef:
                name: ftrade-minibot-binance-secret
