apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret-binance.yaml
  - secret-kucoin.yaml
  - 01-binance-ethusdt-1m.yaml
  - 02-binance-xrpusdt-1m.yaml
  - 03-kucoin-xrpusdt-1m.yaml
  - 04-binance-btcusdt-1m.yaml
  - 05-kucoin-ethusdt-1m.yaml
  - 06-kucoin-btcusdt-1m.yaml
  - 07-binance-bnbusdt-1m.yaml
  - 08-kucoin-bnbusdt-1m.yaml
  - 09-binance-ethusdt-5m.yaml
  - 10-binance-ethusdt-3m.yaml
